version: '3.9'
services:
  #backend-api
  smartbrain-api:
    container_name: smartbrain-api
    build: ./
    command: npm run start
    working_dir: /usr/src/smartbrain-api
    ports:
      - "3500:3500"
    volumes:
      - ./:/usr/src/smartbrain-api
  #postgres
  postgres:
    build: ./postgres
    ports:
      - "5432:5432"
  #pgadmin
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=gn01792218@hotmail.com
      - PGADMIN_DEFAULT_PASSWORD=twshhcaala096221
    ports:
      - "5050:80"
